// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxQvcrjG3THm0jGbbYMIPzLIsnqIS3-b4',
    appId: '1:750274790:web:9d4c0adf0576078ac91327',
    messagingSenderId: '750274790',
    projectId: 'remote-tv-controller-db9ae',
    authDomain: 'remote-tv-controller-db9ae.firebaseapp.com',
    storageBucket: 'remote-tv-controller-db9ae.firebasestorage.app',
    measurementId: 'G-JR57Z3Q86E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnFpuRia67mhSY_oj9uCpYbhIA8wnBzVA',
    appId: '1:750274790:android:010c9c1acf2cd857c91327',
    messagingSenderId: '750274790',
    projectId: 'remote-tv-controller-db9ae',
    storageBucket: 'remote-tv-controller-db9ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVk3sHYZIeFURycvAC0xGRjJBdRnZcDh4',
    appId: '1:750274790:ios:ce1eb425b311db97c91327',
    messagingSenderId: '750274790',
    projectId: 'remote-tv-controller-db9ae',
    storageBucket: 'remote-tv-controller-db9ae.firebasestorage.app',
    iosBundleId: 'com.example.remoteControllerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVk3sHYZIeFURycvAC0xGRjJBdRnZcDh4',
    appId: '1:750274790:ios:ce1eb425b311db97c91327',
    messagingSenderId: '750274790',
    projectId: 'remote-tv-controller-db9ae',
    storageBucket: 'remote-tv-controller-db9ae.firebasestorage.app',
    iosBundleId: 'com.example.remoteControllerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxQvcrjG3THm0jGbbYMIPzLIsnqIS3-b4',
    appId: '1:750274790:web:63e19fbf9974d0fdc91327',
    messagingSenderId: '750274790',
    projectId: 'remote-tv-controller-db9ae',
    authDomain: 'remote-tv-controller-db9ae.firebaseapp.com',
    storageBucket: 'remote-tv-controller-db9ae.firebasestorage.app',
    measurementId: 'G-PFWFWJXP83',
  );
}
